apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: index.docker.io/siddhardhan/kaniko-example
    kaniko:
      buildContext:
        localDir: {}
      cache: 
        repo: index.docker.io/siddhardhan/kaniko-example-cache
  cluster:
    namespace: kaniko
    pullSecret: ~/.docker/config.json
    pullSecretName: kaniko-secret
    dockerConfig:
      path: ~/.docker/config.json
      secretName: regcred
deploy:
  kubectl:
    manifests:
      - k8s-*
test:
- image: index.docker.io/siddhardhan/kaniko-example
  structureTests:
  - ./tests/*