apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
  local:
    useDockerCLI: false
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      - k8s-*
