apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: index.docker.io/siddhardhan/skaffold-example
  local:
    useDockerCLI: false
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      - k8s-*
